/// Flutter icons FlutterFirebaseHero
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterFirebaseHero
///      fonts:
///       - asset: fonts/FlutterFirebaseHero.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class FFHIcon {
  FFHIcon._();

  static const _kFontFam = 'FlutterFirebaseHero';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_circled = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe802, fontFamily: _kFontFam);
}
